from . import asset
from . import asset_category
from . import main_assets
from . import location_assets
from . import asset_transfer
from . import asset_disposal
from . import asset_qr_report_wizard
from . import maintenance
from . import maintenance_team
from . import maintenance_calendar
from . import maintenance_report_wizard
from . import asset_report_wizard
from . import asset_transfer_report_wizard
